'use strict';
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const origin = 'http://127.0.0.1:18790';
const output = 'outputs/browser';
fs.mkdirSync(output, { recursive: true });

(async () => {
  const browser = await chromium.launch({ headless: true, args: ['--no-proxy-server'] });
  const context = await browser.newContext({ viewport: { width: 375, height: 812 } });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  try {
    await page.goto(origin);
    await page.waitForLoadState('networkidle');
    await page.getByRole('checkbox', { name: '我已阅读并同意遵守上述声明' }).check();
    await page.getByRole('button', { name: '同意并进入' }).click();
    await page.evaluate(() => navigator.serviceWorker.ready);
    assert(await page.evaluate(() => Boolean(navigator.serviceWorker.controller)));
    await page.screenshot({ path: `${output}/mobile-home.png`, fullPage: true });
    assert(await page.evaluate(() => document.documentElement.scrollWidth === document.documentElement.clientWidth));
    await page.getByRole('button', { name: '打开导航' }).click();
    assert.equal(await page.locator('#drawer').evaluate(e => e.inert), false);
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#drawer').evaluate(e => e.inert), true);
    await page.getByRole('link', { name: '探索软件库', exact: true }).click();
    await page.locator('#filter-open').click();
    await page.locator('#library-query').fill('笔记');
    assert.match(page.url(), /#\/search/);
    await page.locator('#filter-form button[type=submit]').click();
    await page.locator('#search-results .resource-card').waitFor();
    assert.equal(await page.locator('#filters').evaluate(e => e.inert), true);
    const box = await page.locator('#filter-open').boundingBox();
    assert(box.width > box.height, 'Filter button must remain horizontal');
    assert(await page.evaluate(() => document.documentElement.scrollWidth === document.documentElement.clientWidth));
    await page.screenshot({ path: `${output}/mobile-search.png`, fullPage: true });
    await page.locator('#search-results .resource-card').click();
    await page.locator('#detail-title').waitFor();
    await page.waitForLoadState('networkidle');
    assert.equal(await page.locator('.detail-tags .tag--trust').count(), 0);
    assert.equal(await page.locator('.trust-banner--unknown').count(), 1);
    await page.screenshot({ path: `${output}/mobile-detail.png`, fullPage: true });
    await page.setViewportSize({ width: 1440, height: 900 });
    assert(await page.evaluate(() => document.documentElement.scrollWidth === document.documentElement.clientWidth));
    await page.screenshot({ path: `${output}/desktop-detail.png`, fullPage: true });
    const cacheBefore = await page.evaluate(async () => {
      const c = await caches.open('shuxiang-shell-v8'); return (await c.match('/index.php')).text();
    });
    await page.request.get(`${origin}/download.php?source=1&token=invalid`);
    await page.request.get(`${origin}/app-update.json`);
    assert.deepEqual(await page.evaluate(async () => {
      const urls = await Promise.all((await caches.keys()).map(async key => (await (await caches.open(key)).keys()).map(r => r.url)));
      return urls.flat().filter(url => /api\.php|download\.php|app-update\.json/.test(url));
    }), []);
    const cacheAfter = await page.evaluate(async () => (await (await caches.open('shuxiang-shell-v8')).match('/index.php')).text());
    assert.equal(cacheBefore, cacheAfter);
    await page.goto(origin);
    await page.waitForLoadState('networkidle');
    await context.setOffline(true);
    await page.reload();
    await page.locator('#home-title').waitFor();
    await context.setOffline(false);
    await page.reload();
    await page.waitForLoadState('networkidle');
    const login = await context.request.post(`${origin}/api.php?action=login`, { data: { username: 'release_test_author', password: 'Integration_test_20260917!' } });
    assert.equal(login.status(), 200);
    await page.goto(origin+'/#/account');
    await page.reload();
    await page.getByRole('heading', { name: '我的发布', exact: true }).waitFor();
    await page.screenshot({ path: `${output}/desktop-account.png`, fullPage: true });
    await page.locator('.own-resource a[href^="#/edit/"]').first().click();
    await page.locator('#publish-form:not([hidden])').waitFor();
    await page.locator('#publish-form input[name=version]').fill('1.0.1');
    await page.locator('#publish-form button[type=submit]').click();
    await page.waitForURL(/#\/account/);
    await page.getByText('待审核', { exact: true }).first().waitFor();
    const admin = await context.request.post(`${origin}/api.php?action=login`, { data: { username: 'release_test_admin', password: 'Integration_test_20260917!' }, headers: { Origin: origin } });
    assert.equal(admin.status(), 200);
    await page.goto(origin+'/#/admin');
    await page.reload();
    await page.getByRole('button', { name: '审核通过', exact: true }).first().waitFor();
    await page.screenshot({ path: `${output}/desktop-moderation.png`, fullPage: true });
    await page.getByRole('button', { name: '审核通过', exact: true }).first().click();
    await page.getByText('队列已清空', { exact: true }).waitFor();
    assert.deepEqual(errors, []);
    const result = 'Browser PASS: 375px/1440px, drawers, search, detail, PWA registration/offline/cache isolation, author edit, admin review; page errors=0';
    fs.writeFileSync(`${output}/browser-result.txt`, result+'\n');
    console.log(result);
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
